### ISSUE TITLE
右边的 textarea 文本不能被选中复制

### ISSUE THREAD

**Issue by viko16** [zizhengwu/daft-auto-spacing#2]
## 情况：

在最新版的 Chrome 和 Firefox 中均能复现，加了 `disabled` 的 `<textarea>` 会导致文本不能被正常选中
## 建议：
- HTML 内改为 `readonly`，或是
- CSS 加上 `user-select: all`（注意添加浏览器前缀），或是
- JavaScript 加上 `this.select()`
## 我的环境：

> "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36"
> 
> "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:49.0) Gecko/20100101 Firefox/49.0"

**Comment by zizhengwu** [comment]
多谢告知。让我研究下.....

**Comment by zizhengwu** [comment]
其实我不太会 HTML，CSS，和 JavaScript。可以帮我看下 f7ddc7eeb8086798e84e90ee328d6564219a7466 解决问题了吗...多谢。

**Comment by viko16** [comment]
这样改写没问题 👍 

另外原有的样式

``` css
textarea[disabled { background-color: #ffffff }
```

应该要加上 `textarea[readonly]` 了

https://github.com/zizhengwu/daft-auto-spacing/blob/gh-pages/stylesheets/theme.css#L4732-L4759
